version: "3.1"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo

  my-java-app:
    image: my-db
    container_name: java-app
    ports:
      - 8080:8080
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db-prod
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo
